main_string = input("Enter a string: ")
print(any(i.isalnum() for i in main_string))
print(any(i.isalpha() for i in main_string))
print(any(i.isdigit() for i in main_string))
print(any(i.islower() for i in main_string))
print(any(i.isupper() for i in main_string))